name: Bash application test with Github Actions using devcontainers
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test build-Build and run dev container task
      with:
        runCmd: |
          make install

